### ISSUE TITLE
how to play ai?

### ISSUE THREAD

**Issue by cloudjanak** [wallaceicy06/scrabble#1]
is it possiable like below in web-site 
pass the current board and it will return all playable words with starting position and direction.

http://www.lexicalwordfinder.com/?game=Words_With_Friends&layout=1&tiles=gtsfsdf&board=----------------------------------------------------------------------------------------------------------------hello------------------------------------------------------------------------------------------------------------&lexicon=wwf

**Comment by wallaceicy06** [comment]
Hi cloudjanak! This tool looks neat, but it appears that it doesn't have a REST API for interfacing with it. The response looks like standard HTML which would require some annoying parsing. I would encourage you to give it a try though! This is actually quite an old project of mine (most code of which I'm not entirely proud of). It was mainly built to experiment with Java sockets and networking protocols.
